export const API = "http://34.125.39.164";

export const ACTION = {
  GET_POSTS: "GET_POST",
  GET_ONE_POST: "GET_ONE_POST",
  GET_LIKES: "GET_LIKES",
  GET_COMMEMTS: "GET_COMMENTS",
  GET_ERROR_REGISTRATION: "GET_ERROR_REGISTRATION",
  SUCCESS_REGISTER: "SUCCESS_REGISTER",
};
